
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
  application:
    name: PRODUCT-SERVICE

